### ISSUE TITLE
Smart search return doublon

### ISSUE THREAD

**Issue by ghrlt** [antoninhrlt/sherlock#6]
The use of Sherlock smart search, like this : 
```dart
_searchResults = Sherlock(
    elements: _elementList,
    priorities: const {
        'title': 3,
        'description': 2,
    },
).search(input: value).sorted().unwrap();
```

is returning a list of doublon.

This could be linked to the use of `_currentResults` which is being reset at the end of each query even tho smart search is doing multiple queries.

**Comment by antoninhrlt** [comment]
You're right. I found a solution to fix that problem.

The project will be updated tonight
